"""initial marketplace schema

Revision ID: ebe97a1d9c71
Revises: 
Create Date: 2026-09-26 00:03:22.619105
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ebe97a1d9c71'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amenities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('icon_key', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('amenities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_amenities_slug'), ['slug'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=False),
    sa.Column('bio', sa.Text(), nullable=False),
    sa.Column('can_host', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('demo_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('demo_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_demo_sessions_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_demo_sessions_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_demo_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('subtitle', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=False),
    sa.Column('region', sa.String(length=80), nullable=False),
    sa.Column('country', sa.String(length=80), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('property_type', sa.String(length=50), nullable=False),
    sa.Column('nightly_price_minor', sa.Integer(), nullable=False),
    sa.Column('cleaning_fee_minor', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('max_guests', sa.Integer(), nullable=False),
    sa.Column('bedrooms', sa.Integer(), nullable=False),
    sa.Column('beds', sa.Integer(), nullable=False),
    sa.Column('bathrooms', sa.Integer(), nullable=False),
    sa.Column('rating_hundredths', sa.Integer(), nullable=False),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('is_guest_favorite', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('bedrooms >= 0 AND beds > 0 AND bathrooms > 0', name='ck_listing_room_counts'),
    sa.CheckConstraint('cleaning_fee_minor >= 0', name='ck_listing_cleaning_fee_nonnegative'),
    sa.CheckConstraint('max_guests > 0', name='ck_listing_max_guests_positive'),
    sa.CheckConstraint('nightly_price_minor >= 0', name='ck_listing_nightly_price_nonnegative'),
    sa.ForeignKeyConstraint(['host_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_listings_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_listings_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_listings_country'), ['country'], unique=False)
        batch_op.create_index('ix_listings_discovery', ['is_active', 'city', 'category'], unique=False)
        batch_op.create_index(batch_op.f('ix_listings_host_id'), ['host_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_listings_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_listings_property_type'), ['property_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_listings_region'), ['region'], unique=False)

    op.create_table('availability_blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.String(length=160), nullable=False),
    sa.CheckConstraint('end_date > start_date', name='ck_availability_block_valid_dates'),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('availability_blocks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_availability_blocks_listing_id'), ['listing_id'], unique=False)
        batch_op.create_index('ix_availability_blocks_range', ['listing_id', 'start_date', 'end_date'], unique=False)

    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('guest_id', sa.Integer(), nullable=False),
    sa.Column('check_in', sa.Date(), nullable=False),
    sa.Column('check_out', sa.Date(), nullable=False),
    sa.Column('guests', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('nightly_price_minor', sa.Integer(), nullable=False),
    sa.Column('nights', sa.Integer(), nullable=False),
    sa.Column('subtotal_minor', sa.Integer(), nullable=False),
    sa.Column('cleaning_fee_minor', sa.Integer(), nullable=False),
    sa.Column('service_fee_minor', sa.Integer(), nullable=False),
    sa.Column('total_minor', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('idempotency_key', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('confirmed', 'cancelled', 'completed')", name='ck_booking_status'),
    sa.CheckConstraint('check_out > check_in', name='ck_booking_valid_dates'),
    sa.CheckConstraint('guests > 0', name='ck_booking_guests_positive'),
    sa.ForeignKeyConstraint(['guest_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guest_id', 'idempotency_key', name='uq_booking_guest_idempotency')
    )
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.create_index('ix_booking_availability', ['listing_id', 'status', 'check_in', 'check_out'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_guest_id'), ['guest_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_listing_id'), ['listing_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_status'), ['status'], unique=False)

    op.create_table('favorites',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'listing_id')
    )
    op.create_table('listing_amenities',
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('amenity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['amenity_id'], ['amenities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('listing_id', 'amenity_id')
    )
    op.create_table('listing_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('alt_text', sa.String(length=200), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('listing_id', 'sort_order', name='uq_listing_photo_order')
    )
    with op.batch_alter_table('listing_photos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_listing_photos_listing_id'), ['listing_id'], unique=False)

    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('rating BETWEEN 1 AND 5', name='ck_review_rating'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reviews_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reviews_listing_id'), ['listing_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reviews_listing_id'))
        batch_op.drop_index(batch_op.f('ix_reviews_author_id'))

    op.drop_table('reviews')
    with op.batch_alter_table('listing_photos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_listing_photos_listing_id'))

    op.drop_table('listing_photos')
    op.drop_table('listing_amenities')
    op.drop_table('favorites')
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bookings_status'))
        batch_op.drop_index(batch_op.f('ix_bookings_listing_id'))
        batch_op.drop_index(batch_op.f('ix_bookings_guest_id'))
        batch_op.drop_index('ix_booking_availability')

    op.drop_table('bookings')
    with op.batch_alter_table('availability_blocks', schema=None) as batch_op:
        batch_op.drop_index('ix_availability_blocks_range')
        batch_op.drop_index(batch_op.f('ix_availability_blocks_listing_id'))

    op.drop_table('availability_blocks')
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_listings_region'))
        batch_op.drop_index(batch_op.f('ix_listings_property_type'))
        batch_op.drop_index(batch_op.f('ix_listings_is_active'))
        batch_op.drop_index(batch_op.f('ix_listings_host_id'))
        batch_op.drop_index('ix_listings_discovery')
        batch_op.drop_index(batch_op.f('ix_listings_country'))
        batch_op.drop_index(batch_op.f('ix_listings_city'))
        batch_op.drop_index(batch_op.f('ix_listings_category'))

    op.drop_table('listings')
    with op.batch_alter_table('demo_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_demo_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_demo_sessions_token_hash'))
        batch_op.drop_index(batch_op.f('ix_demo_sessions_expires_at'))

    op.drop_table('demo_sessions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('amenities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_amenities_slug'))

    op.drop_table('amenities')
    # ### end Alembic commands ###
